config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  #get "about", to:"about#index"
  get "about-us", to:"about#index", as: :about    #this means we can change URL but keep the same name we have on link_to
 
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  
  get "sign-up", to: "registeration#new"
  post "sign-up", to:"registeration#create"

  get "sign-in", to: "sessions#new"
  post "sign-in", to:"sessions#create"
  #Layout: 
  # get  "what appears in URL", 
  # to: "(controller file and the views folder that need to be created)#(the function inside the Controller class and the html.erb file created in the views folder)"
  delete "logout", to: "sessions#destroy"
  
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
#email:string
#password_digest:string

#password:string virtual
#password_confirmation:string virtual

class User < ApplicationRecord
    has_secure_password
    #going to use the password_digest column and add "password" and "password confirmation" to user
    #uses bcrypt you have to go in Gem file and delete the "#"
    #then run bundle install again

    validates :email, presence: true, format:{ with: /\A[^@\s]+@[^@\s]+\z/, message: "Must be a valid email address"}
    #another way is to go to migarte/use and put null:false in front of "email", this will check it on console level
    #then you have to do rail db:rollback then migrate again so the change goes in effect
    #or rails db:migrate:redo
    # that format called email regex and checks for valid email addresses
    #means your email address needs to have any charachters(\A) that are not space or @,need one @ symbol and again any character 
    #but space(denoted as "^")
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :set_current_user
    
    #means  run this function before anything else

    def set_current_user
        if session[:user_id]
                Current.user = User.find_by(id: session[:user_id])
                #this way(rather than just "find") is better because it wont crash the app if it cant find the user
        end  
    end 

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You Must Be signed in to do that" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
       # flash.now[:notice] = "Logged in Successfully"
        #flash.now[:alert] = "invalid"
        #or flash.alert
        #flashes persist for one more action before going away meaning after the seond click they will go away
        #to fix that flash.now can be used 
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            #send Email
            PasswordMailer.with(user: @user).reset.deliver_now
            #deliver_later does the mailing in the background
            #deliver-now send it right away but it will take processing speed from rails to do it
        end
        redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your Token Has expired, please try again"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your Password was reset successfully,Please sign in"
        else
            render :edit
        end
    end

    private
        def password_params
            params.require(:user).permit(:password, :password_confirmation)
        end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end
    
    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated"

        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registeration_controller.rb
class RegisterationController < ApplicationController
    def new
        @user = User.new
        # @ makes it that variable can be seen by views
    end

    def create
        #render plain: "Thanks"
        #maybe a way to check inside the methods
      #  render plain: params[:user]
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        #this keeps tabs of sign-ins by users by using cookies
        redirect_to root_path, notice:"Successfully created account"
      else
        render :new
      end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice:"Logged Out"
    end

    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            #.authenticate comes from has_secured_password in user.rb
            session[:user_id] = user.id
            redirect_to root_path, notice:"Logged in Successfully"
        else
            flash.alert = "Invalid email or password"
            render :new

        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
     <%= render partial: "shared/flash" %>
     <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class = "d-flex align-items-center justify-content-center">
    <h1>Welcome to Scheduled Tweets</h1>
</div>
  

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

     <% if form.object.errors.any? %>
        <div class = "alert alert-danger">
            <%= form.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %> 
    <!--You need model for the above code to work-->
   <div class = "mb-3">
        <%= form.label :password  %>
        <%= form.password_field :password, class: "form-control", placeholder:"password" %>
    </div>
    <div class = "mb-3">
        <%= form.label :passwod_confirmation %>    
        <%= form.password_field :password_confirmation, class:"form-control", placeholder:"password confirmation" %>
    </div>
    <div>
        <%= form.submit "Sign Up", class:"btn btn-primary" %>
        <!--binding.irb 
         act like a debugger and pause the program where it is-->
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Your Password</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class = "mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control" , placeholder:"email" %>
    </div>

    <%= form.submit "Reset Password", class:"btn btn-primary" %>
<% end %>

app/views/registeration/new.html.erb
<h1> Sign Up</h1>

<%= form_with model: @user, url:sign_up_path do |form| %>
    <!--check your routes in rails routes 
    password field makes charachters to dots
    see forms in bootstrap for classes-->
    <% if form.object.errors.any? %>
        <div class = "alert alert-danger">
            <%= form.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %> 
    <div class = "mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control" , placeholder:"email" %>
    </div>
    <div class = "mb-3">
        <%= form.label :password  %>
        <%= form.password_field :password, class: "form-control", placeholder:"password" %>
    </div>
    <div class = "mb-3">
        <%= form.label :passwod_confirmation %>    
        <%= form.password_field :password_confirmation, class:"form-control", placeholder:"password confirmation" %>
    </div>
    <div>
        <%= form.submit "Sign Up", class:"btn btn-primary" %>
        <!--it can also take string in "" no = or : needed
        needs text "" to use the bootstrap class-->

    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
    <div class="alert alert-info mt-4" role = "alert">
    <!-- Look up alerts in bootstrap
    adding ".inspect" will print the content -->
        <%= flash.notice %>
    </div>
<% end %>
<% if flash.alert %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash.alert %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
   <!-- <a class="navbar-brand" href="/">Navbar</a> -->
    <%= link_to "Navbar", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
         <!-- <a class="nav-link active" aria-current="page" href="/">Home</a>-->
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
          <!-- <a class="nav-link" href="/about">About</a> about_path is your href 
          This lets me to change the name of the route without going in trouble of doing it manually over and over again
          see routs.rb-->
        </li>
      </ul>
      <ul class = "navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
            <li class="nav-item">
                <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
            </li>
            <li class ="nav-item">
                <%= button_to "Log Out", logout_path, method: :delete, class:"nav-link"  %>
            </li>
        <% else %>
            <li class ="nav-item">
                <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
            </li>
            <li class ="nav-item">    
                <%= link_to "Log In", sign_in_path, class: "nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>